#db_connect: root:WOaini1314@(main.bybyte.cn:3306)/nfushop?charset=utf8mb4&loc=Local&parseTime=true
write_db: root:WOaini1314@(main.bybyte.cn:3306)/nfushop?charset=utf8mb4&loc=Local&parseTime=true
read_db:
  - root:123456@(127.0.0.1:3306)/nfushop?charset=utf8mb4&loc=Local&parseTime=true
  - root:123456@(127.0.0.1:3307)/nfushop?charset=utf8mb4&loc=Local&parseTime=true
secretKey: "Fuck"
port: 7777
